name: CI Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          rpm \
          rpm-build \
          libwebkit2gtk-4.0-dev \
          libgtk-3-dev \
          libnotify-dev \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libasound2 \
          libxtst6 \
          xvfb

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npx tsc --noEmit

    - name: Build frontend
      run: npm run build

    - name: Build Electron app (Linux)
      run: npm run electron:build:linux
      env:
        NODE_ENV: production
        ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
        ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: localshare-linux-build
        path: |
          release/*.AppImage
          release/*.zip
          !release/*.blockmap
          !release/*.yml
        retention-days: 7 